tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 3000    # Timeout in seconds.
    php_code_sniffer:
        config:
            standard: "PSR2"
filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
